### ISSUE TITLE
真的不算bug

### ISSUE THREAD

**Issue by irvingming11** [aaronlinv/learn-programming#2]
**描述出现的问题**
我是真的想看看代码，因为你的功能完善得超好，但是你在上传的时候Demo这个package没有这个包名，但是类里有这个包名所以会有一个报错，但是我注释后仍然无法运行，不知道啥原因，idea的运行环境我也配置好了，源文件也转换成了可执行文件但是还是不行，我也很无奈。但是还是有个问题想问一下，如果你的程序某一行什么也没输入，你有做这样的异常处理吗

**bug复现的情况**

**程序预期应达到的效果**

**程序实际的结果**

**备注**

**Comment by irvingming11** [comment]
主要是你上传来的idea的文件结构好乱，我都不知道怎么整了

**Comment by irvingming11** [comment]
我来解释一下，是我的原因，我用IDE打开存在问题，代码是用Eclipse写的，我测试了一遍，没什么问题，具体代码再详细阅读

**Comment by aaronlinv** [comment]
感谢，已经把文件移到Demo1包里，这样目录更清晰了
